-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 14:57:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`affiliation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`affiliation` (
  `affiliation_ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`affiliation_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `author_ID` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `affiliation_ID` INT NOT NULL,
  PRIMARY KEY (`author_ID`),
  INDEX `fk_author_affiliation1_idx` (`affiliation_ID` ASC),
  CONSTRAINT `fk_author_affiliation1`
    FOREIGN KEY (`affiliation_ID`)
    REFERENCES `mydb`.`affiliation` (`affiliation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`editor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editor` (
  `editor_ID` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`editor_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area_of_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area_of_interest` (
  `RI_Code` INT NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RI_Code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manuscript`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manuscript` (
  `manuscript_ID` INT NOT NULL,
  `editor_ID` INT NOT NULL,
  `author_ID` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `status_time_stamp` DATETIME NOT NULL,
  `RI_Code` INT NOT NULL,
  PRIMARY KEY (`manuscript_ID`),
  INDEX `fk_manuscript_editor1_idx` (`editor_ID` ASC),
  INDEX `fk_manuscript_author1_idx` (`author_ID` ASC),
  INDEX `fk_manuscript_areas_of_interest1_idx` (`RI_Code` ASC),
  CONSTRAINT `fk_manuscript_editor1`
    FOREIGN KEY (`editor_ID`)
    REFERENCES `mydb`.`editor` (`editor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manuscript_author1`
    FOREIGN KEY (`author_ID`)
    REFERENCES `mydb`.`author` (`author_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manuscript_areas_of_interest1`
    FOREIGN KEY (`RI_Code`)
    REFERENCES `mydb`.`area_of_interest` (`RI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reviewer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reviewer` (
  `reviewer_ID` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `affiliation_ID` INT NOT NULL,
  PRIMARY KEY (`reviewer_ID`),
  INDEX `fk_reviewer_affiliation1_idx` (`affiliation_ID` ASC),
  CONSTRAINT `fk_reviewer_affiliation1`
    FOREIGN KEY (`affiliation_ID`)
    REFERENCES `mydb`.`affiliation` (`affiliation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manuscript_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manuscript_review` (
  `manuscript_ID` INT NOT NULL,
  `reviewer_ID` INT NOT NULL,
  `date_assigned` DATETIME NOT NULL,
  `appropriateness` INT NULL,
  `clarity` INT NULL,
  `methodology` INT NULL,
  `contribution` INT NULL,
  `recommendation` TINYINT(1) NULL,
  `date_reviewed` DATETIME NULL,
  PRIMARY KEY (`manuscript_ID`, `reviewer_ID`),
  INDEX `fk_manuscript_has_reviewer_reviewer1_idx` (`reviewer_ID` ASC),
  INDEX `fk_manuscript_has_reviewer_manuscript1_idx` (`manuscript_ID` ASC),
  CONSTRAINT `fk_manuscript_has_reviewer_manuscript1`
    FOREIGN KEY (`manuscript_ID`)
    REFERENCES `mydb`.`manuscript` (`manuscript_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manuscript_has_reviewer_reviewer1`
    FOREIGN KEY (`reviewer_ID`)
    REFERENCES `mydb`.`reviewer` (`reviewer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secondary_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secondary_author` (
  `manuscript_ID` INT NOT NULL,
  `rank` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  INDEX `fk_secondary_author_manuscript1_idx` (`manuscript_ID` ASC),
  PRIMARY KEY (`manuscript_ID`, `rank`),
  CONSTRAINT `fk_secondary_author_manuscript1`
    FOREIGN KEY (`manuscript_ID`)
    REFERENCES `mydb`.`manuscript` (`manuscript_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`issue` (
  `pub_year` INT NOT NULL,
  `period_num` INT NOT NULL,
  `total_pages` INT NULL,
  `print_date` DATETIME NULL,
  PRIMARY KEY (`pub_year`, `period_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manuscript_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manuscript_final` (
  `manuscript_ID` INT NOT NULL,
  `num_pages` INT NULL,
  `order_in_issue` INT NULL,
  `start_page` INT NULL,
  `pub_year` INT NOT NULL,
  `period_num` INT NOT NULL,
  PRIMARY KEY (`manuscript_ID`),
  INDEX `fk_manuscript_final_issue1_idx` (`pub_year` ASC, `period_num` ASC),
  CONSTRAINT `fk_manuscript_final_manuscript1`
    FOREIGN KEY (`manuscript_ID`)
    REFERENCES `mydb`.`manuscript` (`manuscript_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manuscript_final_issue1`
    FOREIGN KEY (`pub_year` , `period_num`)
    REFERENCES `mydb`.`issue` (`pub_year` , `period_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reviewer_interest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reviewer_interest` (
  `reviewer_ID` INT NOT NULL,
  `RI_Code` INT NOT NULL,
  PRIMARY KEY (`reviewer_ID`, `RI_Code`),
  INDEX `fk_reviewer_has_areas_of_interest_areas_of_interest1_idx` (`RI_Code` ASC),
  INDEX `fk_reviewer_has_areas_of_interest_reviewer1_idx` (`reviewer_ID` ASC),
  CONSTRAINT `fk_reviewer_has_areas_of_interest_reviewer1`
    FOREIGN KEY (`reviewer_ID`)
    REFERENCES `mydb`.`reviewer` (`reviewer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviewer_has_areas_of_interest_areas_of_interest1`
    FOREIGN KEY (`RI_Code`)
    REFERENCES `mydb`.`area_of_interest` (`RI_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
